---
# file: roles/system_preferences/tasks/main.yml

###############################################################################
# Desktop & Screen Saver                                                      #
###############################################################################

- name: Enable Screen Saver and Start after 5 Minutes
  osx_defaults:
    host: currentHost
    domain: com.apple.screensaver
    key: idleTime
    type: int
    value: 300

###############################################################################
# Language & Region                                                           #
###############################################################################

#- name: Set Preferred language
#  osx_defaults:
#    domain: NSGlobalDomain
#    key: AppleLanguages
#    type: array
#    value:
#      - en-AU
#    state: present

- name: Set Region
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    type: string
    value: en_AU
    state: present

###############################################################################
# Security & Privacy                                                          #
###############################################################################

- name: Require password after sleep or screen saver begins
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1
    state: present

- name: Password grace period of 5 seconds
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: float
    value: 5
    state: present

- name: Turn on application level firewall and block all incoming connections
  osx_defaults:
    domain: /Library/Preferences/com.apple.alf
    key: globalstate
    type: int
    value: 2
    state: present
  become: true

- name: Check if administrator password is required to access system-wide preferences
  shell: |
    /usr/bin/security authorizationdb read system.preferences > /tmp/system.preferences.plist
    /usr/libexec/PlistBuddy -c "Print :shared" /tmp/system.preferences.plist
  register: shared
  changed_when: false

- name: Require an administrator password to access system-wide preferences
  shell: |
    /usr/libexec/PlistBuddy -c "Set :shared false" /tmp/system.preferences.plist
    /usr/bin/security authorizationdb write system.preferences < /tmp/system.preferences.plist
    rm /tmp/system.preferences.plist
  become: true
  when: shared.stdout != "false"

#- name: Disable remote control infrared receiver
#  osx_defaults:
#    domain: /Library/Preferences/com.apple.driver.AppleIRController
#    key: DeviceEnabled
#    type: boolean
#    value: false
#    state: present
#  become: true

###############################################################################
# Energy Saver                                                                #
###############################################################################

- name: Show battery percentage
  osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: YES
    state: present
  when: '"MacBookPro" in ansible_model'

###############################################################################
# Trackpad                                                                    #
###############################################################################

- name: Enable 'Tap to click' trackpad preference
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: integer
    value: 1
    state: present

- name: Enable 'Tap to click' trackpad driver preferences
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: integer
    value: 1
    state: present

- name: Enable 'Tap to click' in Trackpad preferences panel
  osx_defaults:
    host: currentHost
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: integer
    value: 1
    state: present

- name: Enable 'Secondary click' trackpad preferences
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadRightClick
    type: boolean
    value: true
    state: present

- name: Enable 'Secondary click' trackpad driver preferences
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadRightClick
    type: boolean
    value: true
    state: present

- name: Enable 'Secondary click' in Trackpad preference panel
  osx_defaults:
    host: currentHost
    domain: NSGlobalDomain
    key: com.apple.trackpad.enableSecondaryClick
    type: boolean
    value: true
    state: present

###############################################################################
# Users & Groups                                                              #
###############################################################################

- name: Disable Guest user account
  osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: GuestEnabled
    type: boolean
    value: false
    state: present
  become: true

#- name: Disable Guest access to shared folders (AppleFileServer)
#  osx_defaults:
#    domain: /Library/Preferences/com.apple.AppleFileServer
#    key: guestAccess
#    type: boolean
#    value: false
#    state: present
#  become: true

#- name: Disable Guest access to shared folders (SMB)
#  osx_defaults:
#    domain: /Library/Preferences/SystemConfiguration/com.apple.smb.server
#    key: AllowGuestAccess
#    type: boolean
#    value: false
#    state: present
#  become: true

###############################################################################
# Date & Time                                                                 #
###############################################################################

- name: Check Time Zone
  command: systemsetup -gettimezone
  become: true
  register: tz
  changed_when: false

- name: Set Time Zone
  command: systemsetup -settimezone Australia/Melbourne
  become: true
  when: 'tz.stdout != "Time Zone: Australia/Melbourne"'

- name: Set Clock to be digital
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: IsAnalog
    type: boolean
    value: false
    state: present

#- name: Flash the time separators
#  osx_defaults:
#    domain: com.apple.menuextra.clock
#    key: FlashDateSeparators
#    type: boolean
#    value: true
#    state: present

#- name: Set Clock format to EEE HH:mm
#  osx_defaults:
#    domain: com.apple.menuextra.clock
#    key: DateFormat
#    type: string
#    value: "EEE HH:mm"
#    state: present

###############################################################################
# Safari                                                                      #
###############################################################################

- name: Open with all windows from last session
  osx_defaults:
    domain: com.apple.Safari
    key: AlwaysRestoreSessionAtLaunch
    type: boolean
    value: true
    state: present

- name: Ask websites not to track me
  osx_defaults:
    domain: com.apple.Safari
    key: SendDoNotTrackHTTPHeader
    type: boolean
    value: true
    state: present

- name: Disable AutoFill Contacts
  osx_defaults:
    domain: com.apple.Safari
    key: AutoFillFromAddressBook
    type: boolean
    value: false
    state: present

- name: Disable AutoFill Passwords
  osx_defaults:
    domain: com.apple.Safari
    key: AutoFillPasswords
    type: boolean
    value: false
    state: present

- name: Disable AutoFill Credit cards
  osx_defaults:
    domain: com.apple.Safari
    key: AutoFillCreditCardData
    type: boolean
    value: false
    state: present

- name: Disable AutoFill Other forms
  osx_defaults:
    domain: com.apple.Safari
    key: AutoFillMiscellaneousForms
    type: boolean
    value: false
    state: present

- name: Show Safari status bar
  osx_defaults:
    domain: com.apple.Safari
    key: ShowStatusBar
    type: boolean
    value: true
    state: present
