epson_wf_3620:
  installed: "/Applications/Epson Software/"
  disk_image: "{{ ansible_user_dir }}/Library/Mobile Documents/com~apple~CloudDocs/Disk Images/epson18532.dmg"
  installer: "/Volumes/WF-3620/EPSON.app/Contents/MacOS/EpsonInstaller"
  mount_point: "/Volumes/WF-3620"
